#%RAML 1.0
title: API Gestión Pago de Servicios Públicos
description: Servicio web que permite gestionar el pago de facturas de servicios públicos independientemente del convenio (empresa de servicios públicos)
version: '0.1'
mediaType: application/json
protocols:
  - HTTP
  - HTTPS
baseUri:
  value: 'https://example.com/type/metodo'
types:
  factura:
    description: Entity
    type: object
    properties:
      Idfactura:
        required: true
        example: 1001234
        type: integer
      valorFactura:
        required: false
        example: 130000
        description: Valor a pagar
        type: number
'/{type}':
  /getInfoFactura:
    get:
      description: Permite conocer el valor de una factura
      responses:
        '200':
          description: Devuelve numero de factura y valor a pagar
          body:
            application/json:
              type: factura
        '400':
          description: 'Error, Metodo no existe'
        '404':
          description: 'Error ,falta un parametro'
    '/{idfactura}':
      get:
        description: Devuelve Numero de Factura
        responses:
          '200':
            description: Numero de Factura
            body:
              application/json:
                type: factura
          '400':
            description: 'Error, no existe factura'
          '404':
            description: Numero de Factura no existe
      uriParameters:
        idfactura:
          example: 100345
          description: Numero de Factura
          type: integer
  /pagarFactura:
    post:
      description: Permite cancelar el valor de la factura
      responses:
        '200':
          description: ok
        '400':
          description: Error Numero de factura no valido
    '/{idfactura}':
      post:
        description: Numero de factura a pagar
        queryParameters:
          idfactura:
            example: 100345
            type: integer
      '/{valorfactura}':
        post:
          description: Valor de la factura a pagar
          queryParameters:
            valorfactura:
              example: Example
              description: valor a pagar
              type: string
  /compensarFactura:
    delete:
      description: Permite Eliminar una factura luego de recibir el pago
      responses:
        '404':
          description: Acción No Encontrada
    '/{idfactura}':
      delete:
        description: Factura a Eliminar (compensar) una factura
        responses:
          '200':
            description: Factura Compensada Exitosamente
          '404':
            description: Factura No encontrada