#%RAML 1.0
title: API Gestión Pago de Servicios Públicos
description: Servicio web que permite gestionar el pago de facturas de servicios públicos independientemente del convenio (empresa de servicios públicos)
version: '0.2'
mediaType: application/json
protocols:
  - HTTP
  - HTTPS
baseUri:
  value: 'https://example.com/type/metodo'
types:
  factura:
    description: Entity
    type: object
    properties:
      Idfactura:
        required: true
        example: 1001234
        type: integer
      valorFactura:
        required: false
        example: 130000
        description: Valor a pagar
        type: number
/getInfoFactura:
  get:
    description: Permite conocer el valor de una factura
    responses:
      '200':
        description: Devuelve numero de factura y valor a pagar
        body:
          application/json:
            type: factura
      '400':
        description: 'Error, Metodo no existe'
      '404':
        description: 'Error ,falta un parametro'
  '/type/{type}':
    uriParameters:
      type:
        example: rest
        description: Tipo de servicio web
        type: string
    '/idfactura/{idfactura}':
      uriParameters:
        idfactura:
          example: 100345
          description: Numero de Factura
          type: integer
/pagarFactura:
  /:
    post:
      description: Valor de la factura a pagar
      responses:
        '200':
          body:
            application/json:
              example: Example Pagada Exitosamente
              type: string
  '/type/{type}':
    uriParameters:
      type:
        example: REST
        description: Tipo de servicio
        type: string
    '/idfactura/{idfactura}':
      uriParameters:
        idfactura:
          example: '1003255'
          description: ' '
          type: string
      '/valorFactura/{valorfactura}':
        uriParameters:
          valorfactura:
            example: 300010
            type: number
/compensarFactura:
  delete:
    description: Permite Eliminar una factura luego de recibir el pago
    responses:
      '200':
        description: Respuesta satisfactoria
        body:
          text/plain:
            example: Factura Compensada Exitosamente
            type: string
      '404':
        description: Respuesta con error
        body:
          text/plain:
            example: Acción No Encontrada
            type: string
  uriParameters:
    type:
      example: Example
      description: Tipo de Servicio web
      type: string
  '/type/{type}':
    uriParameters:
      type:
        example: REST
        description: Tipo de servicio Web
        type: string
    '/idfactura/{idfactura}':
      uriParameters:
        idfactura:
          example: 100345
          description: Property description
          type: integer